### ISSUE TITLE
Static Test Reports

### ISSUE THREAD

**Issue by FlippieCoetser** [wallabyjs/wallaby-2794#1]
@smcenlly thanks for setting up this demo project! I am amazed by the simplicity. It just works! 
My license expired but I will renew it straight away.

**I have one question though: Is there a way to generate static HTML Reports on demand?**

During development, I will be using VSCode but when I check the change into Git I would like to run the same set of tests and attached a static report.

**Comment by smcenlly** [comment]
> I have one question though: Is there a way to generate static HTML Reports on demand?

Wallaby does not provide a feature to generate static reports and does not run outside of your editor (i.e. does not have a CLI runner).

For browser-based tests, I would suggest setting up your CLI / CI tests using something like [`karma`](https://karma-runner.github.io/latest/index.html) with jasmine. This [medium post](https://ivantay2003.medium.com/setting-up-karma-with-jasmine-791d83a71fc4) (found after quick google search) may help. I think that the test that I wrote should just work using karma/jasmine - you will need to work out how to get karma to transform your TypeScript files. Another quick google search found this: [karma-typescript](https://www.npmjs.com/package/karma-typescript)
